spring:
  profiles:
    default: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
server:
  port: 8880

jwt:
  secret: dfsfnlskavnflksnfvlaskdnvf1iewe
  expirationTime: 1440